### PR TITLE
Feature: custom ALPN - better header generation and proxy handling

### PR DESCRIPTION
**Pull request by petrpatek**
This solves the proxy usage on HTTP 1.1. It also adds one new feature - the headers are generated correctly by default, the user does not have to know which HTTP version is by the website.

### CODE REVIEW

**Review by mnmkng — APPROVED** [review]
Looks good to me, please test it thoroughly manually on multiple websites before we release it as latest, because it will auto-install on new builds, so we need to be sure it will not break anything.

Also, pls bump version and update changelog.

**Comment by szmarczak** [comment]
I think you can just use https://github.com/szmarczak/http2-wrapper#http2autoprotocolcache
Please note that the change will be visible globally.

```js
http2wrapper.auto.protocolCache.clear();
```

or

```js
http2wrapper.auto.protocolCache = {
	has(name) {
		return false;
	},
	get(name) {},
	set(name, value) {}
};
```

**Comment by mnmkng** [comment]
@szmarczak We'll try to remember with @petrpatek what the real issues were back then. Maybe we made it unnecessarily complicated, because we were not aware of something back then.

But since you're here, do you think it's possible to resolve the protocol using a proxy? 

The thing is, with the current implementation, we always do at least one request to the target website without a proxy, which leaks our real IP. 

And also we block proxy-less requests on our platform on DNS level to prevent access to some hosts without a proxy, but those requests then fail to resolve protocol obviously.

**Comment by szmarczak** [comment]
> do you think it's possible to resolve the protocol using a proxy?

Yep. The way it works it just makes a real TLS connection and reuses the socket if possible.

I'd have to update [`resolve-alpn`](resolve-alpn) to accept the `createConnection` option.

**Comment by szmarczak** [comment]
@mnmkng I think I figured it out. When using `http2wrapper.auto` it reuses the socket from the ALPN negotiation. This is the non-proxied socket. So it makes sense you don't use `http2wrapper.auto` but `http2wrapper.request` :+1:

**Comment by szmarczak** [comment]
It's now possible to mitigate this using `http2.auto` (`http2.request` will work as well): https://github.com/szmarczak/http2-wrapper#proxy-support

Released `http2-wrapper@2.1.0`

**Pull request merged**
